### ISSUE TITLE
files

### ISSUE THREAD

**Issue by markbucko12341** [HumanTree92/esx_customui#1]
there no files dude lol

**Comment by HumanTree92** [comment]
Thats the point. I have many people coming to me asking for the UI. So instead i have made this to troll those people who can't rape their head around the fact that the UI will never be released.

**Comment by ElPumpo** [comment]
haha

**Comment by HumanTree92** [comment]
@ElPumpo You like.

**Comment by ElPumpo** [comment]
I in fact did. Dont worry I dmcad all the repos

**Comment by HumanTree92** [comment]
I figured it was chubbs that did it. But glad they are all gone. I might use this repo for the new HUD that I've been working on.

**Comment by ElPumpo** [comment]
Chubbs is too lazy to care
